version: "3"
services:
  mvf-service:
    container_name: mvf-service
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./src:/var/www/service
    command: tail -f /dev/null
